OPENCV_DIR = /home/yuanyong/lib/opencv

CXX=g++
CXXFLAGS = -std=c++0x -O3 -g -Wall -fmessage-length=0 -I$(OPENCV_DIR)/include
LDFLAGES = $(OPENCV_DIR)/build/lib

all: testReadJson

readJson.o: readJson.h readJson.cpp
	$(CXX) $(CXXFLAGS) -c readJson.cpp -o readJson.o

testReadJson.o: testReadJson.cpp
	$(CXX) $(CXXFLAGS) -c testReadJson.cpp -o testReadJson.o 

testReadJson: readJson.o
	$(CXX) $(CXXFLAGS) $(LDFLAGES) -o testReadJson testReadJson.o readJson.o	